name: Continuous Integration

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchains
        run: rustup target add riscv64gc-unknown-none-elf --toolchain nightly

      - name: Build
        run: make -C ./os build

        # Only run tests when successfully built
      - name: Setup Qemu
        run: bash setup-qemu.sh

      - name: Run
        run: make -C ./os run

  code-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cargo Clippy
        run: make clippy
