name: Sync to GitLab

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GITLAB_USER: neuqOS

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to GitLab
        run: |
          git remote add gitlab https://${{ env.GITLAB_USER}}:${{ secrets.GITLAB_TOKEN }}@gitlab.eduxiji.net/neuqOS/neuq-rcore.git
          git push --all gitlab
          git push --tags gitlab
